### ISSUE TITLE
How do I set the minified prepend URL?

### ISSUE THREAD

**Issue by NullVoxPopuli** [netguru/ember-cli-deploy-rollbar#16]
like... How do I even get the information that goes in it? can it *just* be my domain URL?
I feel like there needs to be more information about this...

**Comment by NullVoxPopuli** [comment]
```javascript
   ENV.rollbar = {
      accessToken: 'client token' from rollbar,
      accessServerToken: 'server token from rollbar',
      minifiedPrependUrl: function(context){
        return [
          'https://s3.amazonaws.com/aeonvera-production/ember/assets/' + context.revisionData.revisionKey,
          'https://s3.amazonaws.com/aeonvera-production/ember/assets/'
        ];
      }
    };
```

this is what I have .. ember/assets/ is the folder where the js and maps are located, when an error occurs, rollbar isn't even attempted to be contacted :-(

**Comment by NullVoxPopuli** [comment]
I'm pretty sure this addon doesn't work for ember 2 :_\

**Comment by jniechcial** [comment]
I will validate if it breaks on ember 2 during weekend on early next week.

In the meantime: `minifedPrependURL` is necessary for Rollbar, not for `ember-cli-deploy-rollbar`, that's why it is not very extensively described. [More information about this can be found on Rollbar site.](https://rollbar.com/docs/source-maps/)

Summing Rollbar docs up, it should be URL that is pointing to directory that is storing your minified JS. For example, if you are using S3 to store your assets, it should be exactly same as in your `ember-cli-deploy.js` file where you defined a fingerprint prepend option ([like here](http://ember-cli.com/user-guide/#fingerprinting-and-cdn-urls)). My assets are stored in my bucket on S3 and I am using following settings (hope it helps you by similarity):
```
(...)
minifiedPrependUrl: 'https://ember-deploy-test-kubanie.s3.eu-central-1.amazonaws.com/',
(...)
```

**Comment by NullVoxPopuli** [comment]
I don't have an ember-cli-deploy.js? just a deploy.js. not sure if it's the same :-\
here it is: https://github.com/NullVoxPopuli/aeonvera-ui/blob/master/config/deploy.js

I set the bucket, and the prefix, which I guess evaluates to:

https://aeonvera-{env}.aws-domain.com/ember

so, that would be the minifiedprependURL, cool, thanks!  I'll see if this fixes anything.

**Comment by jniechcial** [comment]
Sorry for misleading, I meant `ember-cli-build`. [You have it here](https://github.com/NullVoxPopuli/aeonvera-ui/blob/master/ember-cli-build.js#L12)

You should just make them the same (without the `/assets` and so on).

**Comment by NullVoxPopuli** [comment]
I'm going to say this is closed, cause now I think I have a different, more specific issue

**Comment by NullVoxPopuli** [comment]
ok, I finally found out what it was. I was causing an error that was caught, yet still printing to the console.. so I *thought* that it would print, but didn't. Thanks for your help! sorry for flooding the issues with my problems. :-)

**Comment by jniechcial** [comment]
No problem! Have fun with my addon :)
